[build]
  command = "npm run build"
  # Le plugin @netlify/plugin-nextjs gère automatiquement le répertoire de publication
  # Ne pas définir 'publish' ici pour laisser le plugin le gérer

[[plugins]]
  package = "@netlify/plugin-nextjs"


